services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: taskfy-api
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    restart: always
    ports:
    - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - custom_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    # Uncomment this if you need to access the db from an external network
    # ports:
    #   - "1433:1433"
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - custom_network

volumes:
  sqlserver_data:
    driver: local

networks:
  custom_network:
    driver: bridge
